language: python
python:
  - "2.6"
  - "2.7"
install:
  # Build/test dependencies
  - pip install -r requirements.txt --use-mirrors
  # Get fab to test fab
  - pip install -e .
  # Deal with issue on Travis builders re: multiprocessing.Queue :(
  - "sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm"
  # Jinja2 for some tests, in a version that isn't broken on 2.5 :(
  - 'pip install "jinja2<2.7"'
before_script:
  # Allow us to SSH passwordless to localhost
  - ssh-keygen -f ~/.ssh/id_rsa -N ""
  - cp ~/.ssh/{id_rsa.pub,authorized_keys}
script:
  # Normal tests
  - fab test
  # Integration tests
  - fab -H localhost test:"--tests\=integration"
  # Ensure documentation runs OK.
  # Run 'docs' first since its objects.inv is referred to by 'www'.
  # Also force warnings to be errors since most of them tend to be actual
  # problems.
  - invoke docs -o -W
  - invoke www -o -W
notifications:
  irc:
    channels: "irc.freenode.org#fabric"
    template:
      - "%{repository}@%{branch}: %{message} (%{build_url})"
    on_success: change
    on_failure: change
    use_notice: true
  email: false
