language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
install:
  # Build/test dependencies
  - pip install -r requirements.txt --use-mirrors
  # Get fab to test fab
  - pip install -e .
  # Install third-party multiprocessing on 2.5
  - "[[ $TRAVIS_PYTHON_VERSION == '2.5' ]] && pip install multiprocessing"
script: fab test
notifications:
  irc: "irc.freenode.org#fabric"
